RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=12G
             --local-directory=/tmp/
             --scheduler-file=/root/work/cugraph/mg_utils/dask-scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-06-22 20:46:14,107 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:42067'
2023-06-22 20:46:14,111 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:39451'
2023-06-22 20:46:14,112 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:45981'
2023-06-22 20:46:14,114 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:40465'
2023-06-22 20:46:14,117 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:43891'
2023-06-22 20:46:14,119 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:39005'
2023-06-22 20:46:14,122 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:42945'
2023-06-22 20:46:14,124 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:35473'
2023-06-22 20:46:15,508 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,509 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,589 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,589 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,636 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,636 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,637 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,637 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,637 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,637 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,637 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,638 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,638 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,639 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,643 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 20:46:15,643 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 20:46:15,929 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,012 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,057 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,074 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,085 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,085 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,087 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:16,093 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 20:46:18,599 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:36051
2023-06-22 20:46:18,599 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:36051
2023-06-22 20:46:18,599 - distributed.worker - INFO -          dashboard at:        10.33.227.169:38821
2023-06-22 20:46:18,599 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,599 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,599 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,600 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,600 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-qilm9g70
2023-06-22 20:46:18,600 - distributed.worker - INFO - Starting Worker plugin PreImport-08153567-02cd-486d-9e1b-ba194da268a9
2023-06-22 20:46:18,600 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-9938505e-3aaa-4084-8e06-7c127a809f5b
2023-06-22 20:46:18,600 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:40709
2023-06-22 20:46:18,601 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:40709
2023-06-22 20:46:18,601 - distributed.worker - INFO - Starting Worker plugin RMMSetup-792a2ce3-ff3d-447d-8fdc-021e36788ecd
2023-06-22 20:46:18,601 - distributed.worker - INFO -          dashboard at:        10.33.227.169:42907
2023-06-22 20:46:18,601 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,601 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,601 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,601 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,601 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-0yevnto9
2023-06-22 20:46:18,602 - distributed.worker - INFO - Starting Worker plugin PreImport-49933aba-d846-4572-995d-265fb87c9133
2023-06-22 20:46:18,602 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-0ed9fb61-9030-4450-beda-8a74f9beb59b
2023-06-22 20:46:18,602 - distributed.worker - INFO - Starting Worker plugin RMMSetup-119b273c-a52e-4aaa-ad5a-d9cb8c79336b
2023-06-22 20:46:18,605 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:34107
2023-06-22 20:46:18,605 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:34107
2023-06-22 20:46:18,605 - distributed.worker - INFO -          dashboard at:        10.33.227.169:35109
2023-06-22 20:46:18,605 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,605 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,605 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,605 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,605 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-a1pxc717
2023-06-22 20:46:18,606 - distributed.worker - INFO - Starting Worker plugin RMMSetup-827d0831-dc1a-4e2e-9a56-6122758c1c87
2023-06-22 20:46:18,606 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:37379
2023-06-22 20:46:18,606 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:37379
2023-06-22 20:46:18,606 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:42213
2023-06-22 20:46:18,607 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:42213
2023-06-22 20:46:18,607 - distributed.worker - INFO -          dashboard at:        10.33.227.169:41261
2023-06-22 20:46:18,607 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,607 - distributed.worker - INFO -          dashboard at:        10.33.227.169:46389
2023-06-22 20:46:18,607 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,607 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,607 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,607 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,607 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,607 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,607 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-7lf2gz4v
2023-06-22 20:46:18,607 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,607 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-vxy76hav
2023-06-22 20:46:18,607 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:33987
2023-06-22 20:46:18,607 - distributed.worker - INFO - Starting Worker plugin PreImport-6679c841-627d-44f8-9e18-341ef709ea97
2023-06-22 20:46:18,607 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:33987
2023-06-22 20:46:18,607 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-5c7fc2f0-a875-434a-8c2b-d7c2b1d28114
2023-06-22 20:46:18,607 - distributed.worker - INFO - Starting Worker plugin RMMSetup-3ad42137-0334-49f7-9a82-6b829a1a7a78
2023-06-22 20:46:18,607 - distributed.worker - INFO -          dashboard at:        10.33.227.169:42727
2023-06-22 20:46:18,607 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:33549
2023-06-22 20:46:18,608 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:33549
2023-06-22 20:46:18,608 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,608 - distributed.worker - INFO -          dashboard at:        10.33.227.169:40683
2023-06-22 20:46:18,608 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,608 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,608 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,608 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,608 - distributed.worker - INFO - Starting Worker plugin RMMSetup-297ef760-7560-4f71-b826-ceb00b979382
2023-06-22 20:46:18,608 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,608 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,608 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,608 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-x5_moopn
2023-06-22 20:46:18,608 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-n10c36do
2023-06-22 20:46:18,608 - distributed.worker - INFO - Starting Worker plugin RMMSetup-4e02b7f4-4d8b-4eac-bf41-539e99c44e01
2023-06-22 20:46:18,609 - distributed.worker - INFO - Starting Worker plugin PreImport-b1b7dac0-8d47-4b35-aea7-6b1e989dd8c8
2023-06-22 20:46:18,609 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-2f7ac2e5-90ae-40fb-8d1a-3e2d503ac92c
2023-06-22 20:46:18,611 - distributed.worker - INFO - Starting Worker plugin RMMSetup-7b750816-8c55-42b2-8730-52ac224bd2ec
2023-06-22 20:46:18,620 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:38349
2023-06-22 20:46:18,620 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:38349
2023-06-22 20:46:18,620 - distributed.worker - INFO -          dashboard at:        10.33.227.169:40413
2023-06-22 20:46:18,620 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 20:46:18,620 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,620 - distributed.worker - INFO -               Threads:                          1
2023-06-22 20:46:18,620 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 20:46:18,620 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-pfugjbbf
2023-06-22 20:46:18,620 - distributed.worker - INFO - Starting Worker plugin PreImport-49ff7376-4288-46af-8a74-40170c78dadc
2023-06-22 20:46:18,621 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-e37b2dbe-b955-4a99-9626-f7e9c1c0dda4
2023-06-22 20:46:18,621 - distributed.worker - INFO - Starting Worker plugin RMMSetup-7d86f9b9-f0a2-4257-b9b4-ae6dee937823
2023-06-22 20:46:18,822 - distributed.worker - INFO - Starting Worker plugin PreImport-b91b8332-b8d0-466c-a746-aaddd80543d9
2023-06-22 20:46:18,822 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-8e617874-91d6-4642-a131-d41e3648236b
2023-06-22 20:46:18,822 - distributed.worker - INFO - Starting Worker plugin PreImport-ac26350a-de95-4dc9-9690-efb2bb6be8d5
2023-06-22 20:46:18,823 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,823 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-57ffbeee-4332-44f2-bd71-5713cba90355
2023-06-22 20:46:18,823 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-3912cf89-64d8-47c1-b50a-5a63d7ac707c
2023-06-22 20:46:18,823 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,823 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,824 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,824 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,824 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,825 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:18,825 - distributed.worker - INFO - Starting Worker plugin PreImport-9ae05497-99e1-4d29-adf6-aa2686746da0
2023-06-22 20:46:18,826 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,066 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,066 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,067 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,068 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,068 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,069 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,069 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,069 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,069 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,070 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,070 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,070 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,070 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,071 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,071 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,072 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,072 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,072 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,073 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,073 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 20:46:19,073 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 20:46:19,074 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,076 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:46:19,076 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 20:47:30,668 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,669 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,670 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,670 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,674 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,675 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,675 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,676 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:30,770 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 20:47:41,680 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,681 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,682 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,701 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,779 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,787 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,890 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:41,893 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 20:47:48,071 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.74s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,071 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,071 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,071 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.75s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,071 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,071 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,072 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:47:48,072 - distributed.core - INFO - Event loop was unresponsive in Worker for 15.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 20:48:21,174 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,174 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,179 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,179 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,179 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,179 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,179 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:21,180 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 20:48:25,502 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,502 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:25,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,209 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,209 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,214 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,214 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,214 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,214 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,214 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,214 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,695 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,696 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,701 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,701 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,701 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,701 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,701 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:26,701 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,168 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,168 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,173 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,173 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,173 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,173 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,173 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,174 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,634 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,634 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,639 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,639 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,639 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,639 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,639 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:27,639 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,104 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,104 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,108 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,109 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,109 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,109 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,109 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,109 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,567 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,569 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,574 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,574 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,575 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,576 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,576 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:28,576 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,033 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,033 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,038 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,502 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,502 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,507 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,508 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,966 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,967 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:29,972 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 20:48:31,131 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,131 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,131 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,131 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,132 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,132 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,132 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 20:48:31,132 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 21:02:10,640 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:33549. Reason: worker-handle-scheduler-connection-broken
2023-06-22 21:02:10,640 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:42067'. Reason: nanny-close
2023-06-22 21:02:10,640 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:33987. Reason: worker-close
2023-06-22 21:02:10,641 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:37379. Reason: worker-close
2023-06-22 21:02:10,641 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:34107. Reason: worker-handle-scheduler-connection-broken
2023-06-22 21:02:10,641 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:38349. Reason: worker-close
2023-06-22 21:02:10,641 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:40709. Reason: worker-close
2023-06-22 21:02:10,641 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:42213. Reason: worker-close
2023-06-22 21:02:10,641 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:36051. Reason: worker-close
2023-06-22 21:02:10,641 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,642 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:39451'. Reason: nanny-close
2023-06-22 21:02:10,643 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,643 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:45981'. Reason: nanny-close
2023-06-22 21:02:10,644 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,644 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:40465'. Reason: nanny-close
2023-06-22 21:02:10,644 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,645 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:43891'. Reason: nanny-close
2023-06-22 21:02:10,645 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,646 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:39005'. Reason: nanny-close
2023-06-22 21:02:10,646 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,644 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:42488 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:02:10,644 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:42494 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:02:10,646 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:42945'. Reason: nanny-close
2023-06-22 21:02:10,644 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:42472 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:02:10,647 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,644 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:42504 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:02:10,644 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:42458 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:02:10,647 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:35473'. Reason: nanny-close
2023-06-22 21:02:10,648 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:02:10,645 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:42518 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:02:10,670 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:40465 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:40320 remote=tcp://10.33.227.169:40465>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:40465 after 100 s
2023-06-22 21:02:10,671 - distributed.core - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:35473 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:47038 remote=tcp://10.33.227.169:35473>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:35473 after 100 s
2023-06-22 21:02:13,850 - distributed.nanny - WARNING - Worker process still alive after 3.199993133544922 seconds, killing
2023-06-22 21:02:13,850 - distributed.nanny - WARNING - Worker process still alive after 3.1999992370605472 seconds, killing
2023-06-22 21:02:13,851 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 21:02:13,852 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing
2023-06-22 21:02:13,852 - distributed.nanny - WARNING - Worker process still alive after 3.1999990844726565 seconds, killing
2023-06-22 21:02:13,852 - distributed.nanny - WARNING - Worker process still alive after 3.1999992370605472 seconds, killing
2023-06-22 21:02:13,852 - distributed.nanny - WARNING - Worker process still alive after 3.1999992370605472 seconds, killing
2023-06-22 21:02:13,852 - distributed.nanny - WARNING - Worker process still alive after 3.1999893188476562 seconds, killing
2023-06-22 21:02:14,623 - distributed.nanny - INFO - Worker process 1394610 was killed by signal 9
2023-06-22 21:02:14,642 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,643 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,645 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,645 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,647 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,647 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,648 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394622 parent=1394575 started daemon>
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394620 parent=1394575 started daemon>
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394616 parent=1394575 started daemon>
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394613 parent=1394575 started daemon>
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394607 parent=1394575 started daemon>
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394604 parent=1394575 started daemon>
2023-06-22 21:02:14,649 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1394601 parent=1394575 started daemon>
2023-06-22 21:02:15,190 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1394604 exit status was already read will report exitcode 255
2023-06-22 21:02:15,303 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1394601 exit status was already read will report exitcode 255
2023-06-22 21:02:15,565 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1394622 exit status was already read will report exitcode 255
