RUNNING: "python -m distributed.cli.dask_scheduler --protocol=tcp
                    --scheduler-file /root/work/cugraph/mg_utils/dask-scheduler.json
                "
/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/cli/dask_scheduler.py:140: FutureWarning: dask-scheduler is deprecated and will be removed in a future release; use `dask scheduler` instead
  warnings.warn(
2023-06-22 21:27:58,195 - distributed.scheduler - INFO - -----------------------------------------------
2023-06-22 21:27:58,767 - distributed.scheduler - INFO - State start
2023-06-22 21:27:58,777 - distributed.scheduler - INFO - -----------------------------------------------
2023-06-22 21:27:58,778 - distributed.scheduler - INFO -   Scheduler at:  tcp://10.33.227.169:8786
2023-06-22 21:27:58,778 - distributed.scheduler - INFO -   dashboard at:  http://10.33.227.169:8787/status
2023-06-22 21:28:09,799 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:39247', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,045 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:39247
2023-06-22 21:28:10,046 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42904
2023-06-22 21:28:10,055 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:46613', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,055 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:46613
2023-06-22 21:28:10,055 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42926
2023-06-22 21:28:10,056 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:35787', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,056 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:35787
2023-06-22 21:28:10,056 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42910
2023-06-22 21:28:10,057 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:39523', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,057 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:39523
2023-06-22 21:28:10,058 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42938
2023-06-22 21:28:10,059 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:36481', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,059 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:36481
2023-06-22 21:28:10,059 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42982
2023-06-22 21:28:10,060 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:41457', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,060 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:41457
2023-06-22 21:28:10,060 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42962
2023-06-22 21:28:10,061 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:43565', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,061 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:43565
2023-06-22 21:28:10,061 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42952
2023-06-22 21:28:10,061 - distributed.scheduler - INFO - Register worker <WorkerState 'tcp://10.33.227.169:41823', status: init, memory: 0, processing: 0>
2023-06-22 21:28:10,062 - distributed.scheduler - INFO - Starting worker compute stream, tcp://10.33.227.169:41823
2023-06-22 21:28:10,062 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42970
2023-06-22 21:29:01,658 - distributed.scheduler - INFO - Receive client connection: Client-ce4a1e0d-1143-11ee-b84a-d8c49778ced7
2023-06-22 21:29:01,659 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:42022
2023-06-22 21:29:01,770 - distributed.worker - INFO - Run out-of-band function '_func_set_scheduler_as_nccl_root'
2023-06-22 21:29:37,503 - distributed.scheduler - INFO - Remove client Client-ce4a1e0d-1143-11ee-b84a-d8c49778ced7
2023-06-22 21:29:37,504 - distributed.core - INFO - Received 'close-stream' from tcp://10.33.227.169:42022; closing.
2023-06-22 21:29:37,504 - distributed.scheduler - INFO - Remove client Client-ce4a1e0d-1143-11ee-b84a-d8c49778ced7
2023-06-22 21:29:37,504 - distributed.scheduler - INFO - Close client connection: Client-ce4a1e0d-1143-11ee-b84a-d8c49778ced7
2023-06-22 21:29:41,678 - distributed._signals - INFO - Received signal SIGINT (2)
2023-06-22 21:29:41,679 - distributed.core - INFO - Connection to tcp://10.33.227.169:42904 has been closed.
2023-06-22 21:29:41,679 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:39247', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,679 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:39247
2023-06-22 21:29:41,680 - distributed.core - INFO - Connection to tcp://10.33.227.169:42970 has been closed.
2023-06-22 21:29:41,680 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:41823', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,680 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:41823
2023-06-22 21:29:41,681 - distributed.scheduler - INFO - Scheduler closing...
2023-06-22 21:29:41,681 - distributed.core - INFO - Connection to tcp://10.33.227.169:42938 has been closed.
2023-06-22 21:29:41,681 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:39523', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,682 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:39523
2023-06-22 21:29:41,683 - distributed.core - INFO - Connection to tcp://10.33.227.169:42962 has been closed.
2023-06-22 21:29:41,683 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:41457', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,683 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:41457
2023-06-22 21:29:41,684 - distributed.core - INFO - Connection to tcp://10.33.227.169:42952 has been closed.
2023-06-22 21:29:41,684 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:43565', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,684 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:43565
2023-06-22 21:29:41,684 - distributed.core - INFO - Connection to tcp://10.33.227.169:42982 has been closed.
2023-06-22 21:29:41,684 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:36481', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,684 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:36481
2023-06-22 21:29:41,685 - distributed.core - INFO - Connection to tcp://10.33.227.169:42910 has been closed.
2023-06-22 21:29:41,685 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:35787', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,685 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:35787
2023-06-22 21:29:41,685 - distributed.core - INFO - Connection to tcp://10.33.227.169:42926 has been closed.
2023-06-22 21:29:41,685 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.33.227.169:46613', status: running, memory: 0, processing: 0>
2023-06-22 21:29:41,685 - distributed.core - INFO - Removing comms to tcp://10.33.227.169:46613
2023-06-22 21:29:41,685 - distributed.scheduler - INFO - Lost all workers
2023-06-22 21:29:41,686 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42910>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 317, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 328, in write
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42910>: Stream is closed
2023-06-22 21:29:41,687 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42982>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 317, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 328, in write
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42982>: Stream is closed
2023-06-22 21:29:41,687 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42938>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 21:29:41,687 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42962>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 317, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 328, in write
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42962>: Stream is closed
2023-06-22 21:29:41,688 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42952>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 317, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 328, in write
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42952>: Stream is closed
2023-06-22 21:29:41,688 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42926>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 317, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 328, in write
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Scheduler connection to worker local=tcp://10.33.227.169:8786 remote=tcp://10.33.227.169:42926>: Stream is closed
2023-06-22 21:29:41,689 - distributed.scheduler - INFO - Scheduler closing all comms
2023-06-22 21:29:41,692 - distributed.scheduler - INFO - Stopped scheduler at 'tcp://10.33.227.169:8786'
2023-06-22 21:29:41,693 - distributed.scheduler - INFO - End scheduler
